### ISSUE TITLE
Question regarding nc-mount application.

### ISSUE THREAD

**Issue by harshawasthi90** [opendaylight/coretutorials#1]
In ncmount application we are using **xrnodes-config.xml** file to make connection to netconf-server.

I want to achieve this programatically with out using any configuration file/making a  restconf.
How can i achieve this functionality?

**Comment by tykeal** [comment]
My apologies, but the issue tracker here should not have been available. This is repo is strictly a mirror of the repo hosted out of https://git.opendaylight.org Please bring your questions to the relevant mailing list on https://lists.opendaylight.org or raise a bug in https://bugs.opendaylight.org.
